<?php
/******************************************************************************
 * Copyright (c) 2017 Constantin Galbenu <gica.galbenu@gmail.com>             *
 ******************************************************************************/

namespace Gica\Cqrs\CodeGeneration;


use Gica\Cqrs\Command\CodeAnalysis\ReadModelEventHandlerDetector;
use Psr\Log\LoggerInterface;
use Gica\CodeAnalysis\MethodListenerDiscovery;
use Gica\CodeAnalysis\MethodListenerDiscovery\ClassSorter\ByConstructorDependencySorter;
use Gica\CodeAnalysis\MethodListenerDiscovery\ListenerClassValidator\AnyPhpClassIsAccepted;
use Gica\CodeAnalysis\MethodListenerDiscovery\MethodListenerMapperWriter;

class ReadModelEventListenersMapCodeGenerator
{
    public function generate(
        LoggerInterface $logger,
        string $eventSubscriberTemplateClassName,
        string $searchDirectory,
        string $outputFilePath,
        string $outputShortClassName
    )
    {
        $classInfo = new \ReflectionClass($eventSubscriberTemplateClassName);

        @unlink($outputFilePath);

        $discoverer = new MethodListenerDiscovery(
            new ReadModelEventHandlerDetector(),
            new AnyPhpClassIsAccepted,
            new ByConstructorDependencySorter()
        );

        $discoverer->discoverListeners($searchDirectory);

        $map = $discoverer->getEventToListenerMap();

        $writer = new MethodListenerMapperWriter();

        $template = file_get_contents($classInfo->getFileName());

        $template = str_replace($classInfo->getShortName() /*EventSubscriberTemplate*/, $outputShortClassName /*EventSubscriber*/, $template);

        $template = str_replace('--- This is just a template ---', '--- generated by ' . __FILE__ . ' at ' . date('c') . ' ---', $template);

        $code = $writer->generateAndGetFileContents($map, $template);

        if (false === file_put_contents($outputFilePath, $code))
            $logger->error("write error");

        chmod($outputFilePath, 0777);

        $logger->info("Read models events handlers map wrote to: $outputFilePath");
    }
}