<?php
/******************************************************************************
 * Copyright (c) 2017 Constantin Galbenu <gica.galbenu@gmail.com>             *
 ******************************************************************************/

namespace Gica\Cqrs\CodeGeneration;


use Psr\Log\LoggerInterface;
use Gica\CodeAnalysis\MethodListenerDiscovery;
use Gica\CodeAnalysis\MethodListenerDiscovery\ClassSorter\ByConstructorDependencySorter;
use Gica\CodeAnalysis\MethodListenerDiscovery\ReadModelMapperWriter;
use Gica\Cqrs\Command\CodeAnalysis\ReadModelEventHandlerDetector;
use Gica\Cqrs\ReadModel\ListenerClassValidator\OnlyReadModels;

class ReadModelsMapCodeGenerator
{
    public function generate(
        LoggerInterface $logger,
        string $readModelMapTemplateClassName,
        string $searchDirectory,
        string $outputFilePath,
        string $outputShortClassName
    )
    {
        $classInfo = new \ReflectionClass($readModelMapTemplateClassName);

        @unlink($outputFilePath);

        $discoverer = new MethodListenerDiscovery(
            new ReadModelEventHandlerDetector(),
            new OnlyReadModels(),
            new ByConstructorDependencySorter()
        );

        $discoverer->discoverListeners($searchDirectory);

        $map = $discoverer->getAllEventsListeners();

        $writer = new ReadModelMapperWriter();

        $template = file_get_contents($classInfo->getFileName());

        $template = str_replace($classInfo->getShortName() /*ReadModelMapTemplate*/, $outputShortClassName /* ReadModelMap */, $template);

        $template = str_replace('--- This is just a template ---', '--- generated by ' . __FILE__ . ' at ' . date('c') . ' ---', $template);

        $code = $writer->generateAndGetFileContents($map, $template);

        if (false === file_put_contents($outputFilePath, $code))
            $logger->error("write error");

        chmod($outputFilePath, 0777);

        $logger->info("Read models map wrote to: $outputFilePath (searched in $searchDirectory)");
    }
}